chore: 調整 lighthouse-ci yml

diff --git a/.github/workflows/lighthouse-action.yml b/.github/workflows/lighthouse-action.yml
--- a/.github/workflows/lighthouse-action.yml
+++ b/.github/workflows/lighthouse-action.yml
@@ -1,5 +1,9 @@
+# 給一個名字
 name: CI
+
+# 設定 Github Action 的 Cron Job 還有需要更新的分支
 on: [push]
+
 jobs:
   lhci:
     name: LighthouseCI
@@ -19,6 +23,6 @@ jobs:
         run: npm run build
 
       - name: LighthouseCI
-        run: lhci autorun
+        run:  lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
